name: Merge Checks

on:
  pull_request:
    # Run for any branch targeting the default branch (main)
    branches: ["main"]

jobs:
  build-test:
    uses: ./.github/workflows/build-test.yml
    with:
      node-version: "22"
